#ifndef PC_CONTROL_VERSION_H
#define PC_CONTROL_VERSION_H

#define PC_CONTROL_VERSION_MAJOR 1
#define PC_CONTROL_VERSION_MINOR 1
#define PC_CONTROL_VERSION_PATCH 1

#define VERSION "1.1.1"
#define PC_CONTROL_VERSION_COMMA PC_CONTROL_VERSION_MAJOR,PC_CONTROL_VERSION_MINOR,PC_CONTROL_VERSION_PATCH,0

#endif
